---
- name: Add SSH public key to remote server
  hosts: all
  become: yes
  vars:
    target_user: "ubuntu"  
    public_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCT/a3MJHQJzFhxDuRtomiVBpKHzJ+" 

  tasks:
    - name: Add public key to authorized_keys
      ansible.builtin.lineinfile:
        path: "/home/{{ target_user }}/.ssh/authorized_keys"
        line: "{{ public_key }}"
        state: present
        create: yes
        mode: '0600'
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
