---
- name: Add multiple SSH public keys to remote server
  hosts: all
  become: yes
  vars:
    target_user: "ubuntu"
    public_keys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCT/a3MJHQJzFhxDuRtomiVBpKHzJ+2baU4XROewVxhvSKJFWmOhJNkIdT4ArojRgsafBfFa2RXA397WP0sC/Yw4DQqw/Z3E"
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOM9NAUIuImpfdZYGBezhjHU4pMSLC+skdIzT5"

  tasks:
    - name: Add public keys to authorized_keys
      ansible.builtin.lineinfile:
        path: "/home/{{ target_user }}/.ssh/authorized_keys"
        line: "{{ item }}"
        state: present
        create: yes
        mode: '0600'
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
      loop: "{{ public_keys }}"
