---
- name: Configure log rotation for multiple fiber nodes
  hosts: all
  become: yes

  tasks:
    - name: Install logrotate if not present
      apt:
        name: logrotate
        state: present
      when: ansible_pkg_mgr == 'apt'

    - name: Configure logrotate for all fiber node logs
      copy:
        dest: /etc/logrotate.d/fiber-nodes
        content: |
          /home/ubuntu/fiber*/logs/node.log {
              hourly
              missingok
              rotate 168
              notifempty
              copytruncate
              dateext
              dateformat -%Y-%m-%d-%H
              sharedscripts
              postrotate
                  [ ! -f /var/run/syslogd.pid ] || kill -USR1 `cat /var/run/syslogd.pid`
              endscript
          }
        owner: root
        group: root
        mode: '0644'

    - name: Add hourly logrotate cron job
      cron:
        name: "Hourly logrotate for fiber logs"
        job: "/usr/sbin/logrotate /etc/logrotate.d/fiber-nodes"
        user: root
        minute: "0"
        state: present          
